name: Draft Release PR
on:
  workflow_run:
    workflows: [Lint and Test]
    branches: [main]
    types:
      - completed
jobs:
  draft-release:
    name: Draft Release PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create or Update Release PR
      run: |
        ./.bin/release-pr.sh
