name: On Push
on: push
jobs:
  lint-test:
    runs-on: ubuntu-latest
    name: Lint & Test
    env:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM & Composer dependencies
        run: |
          composer install
          npm install
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS wordpress_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Install WP Unit tests
        run: |
          php -v
          mysqladmin -V
          bash .bin/install-wp-tests.sh wordpress_test root root localhost latest true
      - name: Run linter
        run: composer lint
      - name: Run tests
        run: composer test
  wporg-code-analysis:
    runs-on: ubuntu-latest
    name: WP.org Code Analysis
    steps:
      - name: WP.org Code Analysis
        uses: actions/checkout@v3
      - name: WP.org Code Analysis
        uses: pantheon-systems/action-wporg-validator@1.0.0
        with:
          type: plugin
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Note these tests may be incomplete for newer PHP version and miss some deprecations"
        shell: bash
      - name: PHPCompatibility
        # using @dev because PHPCompatibility ^9 does not yet have the
        # sniffers for 8.0+ but main branch does
        uses: pantheon-systems/phpcompatibility-action@dev
        with:
          test-versions: 8.0-
  draft-release:
    name: Draft Release PR
    needs:
      - lint-test
      - wporg-code-analysis
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create or Update Release PR
      run: |
        bash .bin/release-pr.sh