name: Validate Plugin Version Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: List all branches
        run: git branch -a
      - name: Validate Plugin Version
        uses: jazzsequence/action-validate-plugin-version@v1
        with:
          filenames: 'readme.txt,README.MD'
          branch: 'release'
          dry-run: true
        