name: Validate Tested Up To Version
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  validate-plugin-version:
    runs-on: ubuntu-latest
    name: Validate Plugin Version
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: jazzsequence/action-validate-plugin-version@v2
        with:
          filenames: 'readme.txt,README.MD'
          branch: 'release'